### ISSUE TITLE
Error GPIO.cpp

### ISSUE THREAD

**Issue by davixcky** [saleem-hadad/zino#2]
In the line 79 of GPIO.cpp there are a double condition similar.
```
int GPIO::read(Pin& pin){
    if (pin.port() == PortB) {
        return (*pinb & (1 << pin.pin())) ? 1 : 0;
    }else if(pin.port() == PortB){
        return (*pind & (1 << pin.pin())) ? 1 : 0;
    }

    return GPIO::analogRead(pin.pin());
}
```

I suppose that in the second `if`, is ``pin.port() == PortD``.

[GPIO.cpp](https://github.com/saleem-hadad/zino/blob/master/src/GPIO.cpp#L79)

**Comment by saleem-hadad** [comment]
Ohh 😓, my mistake I didn't realize that.
Thank you @davixcky 😎🌸

**Comment by davixcky** [comment]
You're welcome

**Comment by davixcky** [comment]
You're welcome
